### ISSUE TITLE
edit/delete post

### ISSUE THREAD

**Issue by snlemons** [talklittle/reddit-is-fun#10]
It would be nice to be able to edit and delete posts and comments from within the app.

**Comment by talklittle** [comment]
Yes, absolutely. This actually should probably be top priority

**Comment by talklittle** [comment]
edit/delete has been implemented for comments.

delete has been implemented for threads.

edit code is there for self-post threads, but commented out because the reddit API only gives us selftext as HTML not plaintext. (for comments it gives us both plaintext and HTML, which is what we want)

**Comment by talklittle** [comment]
KeyserSosa updated the reddit API to include selftext plaintext too, so it is possible to go forward with Edit self posts functionality. I'll do this now.
