### ISSUE TITLE
Suddenly unable to pick subreddit.

### ISSUE THREAD

**Issue by EnsuingRequiem** [talklittle/reddit-is-fun#100]
I can go to comments of items on the start reddit and follow links, etc. If I go to the comments of an item, I can pick go to subreddit and it will take me to the subreddit no problem. If, however, I hit Menu -> Pick Subreddit -> type or select a subreddit, it takes me back to the previous screen. Tried uninstall and reinstall of the Reddit is Fun app to no avail. Done using a Sprint CDMA Hero running Fresh ROM 2.4.

**Comment by talklittle** [comment]
Strange, works for me. I can look into it more when I get some time...

**Comment by EnsuingRequiem** [comment]
Well...I got a little upset with my phone in general and ended up flashing a new ROM. Now running CM6 (Based on Froyo) and installed Reddit is Fun. Eveything is fine. Not sure if something got set funny and the wipe fixed it or what.

**Comment by talklittle** [comment]
Haha, nice. Thanks for the update. I'll close this bug then...
