### ISSUE TITLE
option to not refresh on open

### ISSUE THREAD

**Issue by darrenkopp** [talklittle/reddit-is-fun#101]
really sucks when you are like 8 pages in, go to a page that redirects to mobile, have to spam back button to get to back to reddit is fun but then you go to far and it goes to desktop, and when you open it, bam, refreshes, losing where you were.

i don't blame reddit is fun, i blame the crappy website, but still it is INCREDIBLY frustrating.

**Comment by talklittle** [comment]
Instead of this, I will probably implement #117 the exit confirmation dialog.
