### ISSUE TITLE
Dark Theme loading screen should be completely black

### ISSUE THREAD

**Issue by db0** [talklittle/reddit-is-fun#114]
I love the dark theme of Reddit is Fun on my Galaxy-S which uses an AMOLED display because it really cuts down on the battery usage. However the loading screen of RiF, instead of being completely black (like the background of the main reddit screen in RiF's Dark Theme) is a shade of grey, which still needs to power on the LEDs and therefore consumes power. And unfortunately usually I'm stuck on the loading screen more than I'm be reading the articles. 

So can you please make it so that the loading screen background in the Dark Theme is completely black? Thanks

**Comment by talklittle** [comment]
sure I can see how it looks and adjust if it's ok

but I read that using black only really saves around 2-3% battery life. the real power consumption is in data transmission...

**Comment by db0** [comment]
I don't know about other models, but in my Galaxy-S, 65-80% of the battery is consumed by the display, so obviously cutting down on that is the way to go. ;)

Thanks for considering this btw.

**Comment by talklittle** [comment]
WOW ok thanks for the info

**Comment by ibrahima** [comment]
Also on an AMOLED device the black pixels are actually off, so it looks really good because they're actually fully black. That's also why there's power savings.

**Comment by adamweld** [comment]
Yep, this will effect all AMOLED screen-type devices, such as the SGS line, Nexus One, HTC Desire, etc.
I really hope it is implemented, this is something I've been wanting for a while.

**Comment by talklittle** [comment]
fixed on private development branch
