### ISSUE TITLE
Add r/all to the list of subreddits

### ISSUE THREAD

**Issue by Taedirk** [talklittle/reddit-is-fun#116]
I'd love to see r/all show up in the list of subreddits rather than having to type it out every time.  It's certainly a low priority item, but would be a nice bit of time-saving/streamlining.

**Comment by shawn-simon** [comment]
Came here to suggest this, I'd love this feature

**Comment by shawn-simon** [comment]
I added this feature : )

**Comment by talklittle** [comment]
Thanks teen-!
