### ISSUE TITLE
Battery drain secondary to quit verification

### ISSUE THREAD

**Issue by Ebonyks** [talklittle/reddit-is-fun#120]
I don't know if anyone else has had this issue, but it's irksome enough that i signed up for an account here to comment. Accept my apologies if my presentation of issues is against etiquette. Please eliminate this from the future version of the software, or at least offer a toggle in the settings menu. I drained an entire battery today leaving reddit is fun open today because i simply hit the back button by habit and it didn't close the program, preventing my phone from going into sleep mode.

**Comment by talklittle** [comment]
Taken care of it, thanks for the feedback. It will have an option in tonight's update

**Comment by Ebonyks** [comment]
And thank you for all of the hard work and startlingly fast response time. Keep up the good work.
