### ISSUE TITLE
Go to comment broken

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#122]
Finally figured out why. It's because of the load-on-demand feature for the comments. When jumping to comment, the list item sizes are reported as 0 or something very small. Only after loading the comment do they report the correct size.

I can think of two solutions right now:
1. load comments one at a time in order, not in getView(). jumpToComment() piggybacks, or at least waits until the desired comment has been loaded by that thread, before jumping to it.
2. jumpToComment() fires repeatedly every 100-200ms until scrolling stops. Disadvantages are different load speed on different devices, and possibly user trying to scroll simultaneously.

**Comment by talklittle** [comment]
fixed it. did something simpler than 1. 2 didn't work.

basically in CommentManager (the async comment loader) every time you load a message, call jumpToComment() to try to jump to the original jump-target comment. use OnKeyListener and OnTouchListener to disable the repeated jumps as soon as user triggers a key or touch.

**Comment by afhdyt** [comment]
dear talklittle,

i have a problem which is similar to what you mentioned.

my problem is that comments do not appear.
please see my screenshot: http://imgur.com/vXbdy

maybe you can help me... thank you
