### ISSUE TITLE
[bug]No subreddits since 1.1.1

### ISSUE THREAD

**Issue by corvettecraz92** [talklittle/reddit-is-fun#124]
Ever since a few updates ago, I can't select subreddits. I choose a subreddit, but it goes right back to the page I was on and acts like I did nothing. It was working fine before, and I have changed nothing on my phone before or after that update.

**Comment by talklittle** [comment]
Strange, works for me. Please try uninstalling/reinstalling.

**Comment by corvettecraz92** [comment]
Tried that a few times..still no go. I don't know why it's not working, it just stopped letting me choose subreddits since a few updates ago. I haven't seen anyone else mention that they're having the same problem either.
