### ISSUE TITLE
Exit without error when selecting a post's link

### ISSUE THREAD

**Issue by nikdoof** [talklittle/reddit-is-fun#126]
Clicking to view a posts link will just exit the activity with no action. The app does not force close or produce any errors. I'm available to assist in any debugging work needed to resolve this.

Dell Streak, Android 2.2 OTA image.

**Comment by talklittle** [comment]
Procurement of a logcat log immediately after the crash would be very helpful. Thanks

**Comment by nikdoof** [comment]
This only seems to occur for logged in users, using the app logged out works fine. I'm yet to do a logcat but i'll get it sorted soon.

**Comment by talklittle** [comment]
nikdoof, any word on this bug? Has it happened again?
