### ISSUE TITLE
Jump to comment firing too often

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#127]
Seems like the listener is not being removed fast enough, so will sometimes jump around when you try to scroll.

Maybe instead of the onKeyDown and onTouch, need the CommentsListView overriding onScrollListener()?

**Comment by talklittle** [comment]
comment by github user tobo:

How to recreate:

-Vote on comment
-scroll away
-wait some time
-thread jumps back to voted on comment

Device: HTC Desire, Android 2.2

**Comment by talklittle** [comment]
significantly changed the comment loading algorithm not to use multiple threads, just the single AsyncTask thread. works pretty well!

**Comment by michaelhood** [comment]
confirmed that this fix worked perfectly for me. that was my top usability issue; all better. thanks talklittle!

**Comment by talklittle** [comment]
Great. Thanks for the confirmation!

On Tue, Aug 9, 2011 at 10:52 AM, michaelhood
reply@reply.github.com
wrote:
