### ISSUE TITLE
Tries and fails to intercept .compact links

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#128]
Probably should not even try. I do not want to intercept the mobile site's traffic.

**Comment by talklittle** [comment]
This one is a bit difficult to solve. The intent filter does not have powerful pattern matching, so it is not possible to filter out URLs containing ".compact" that way.

One alternative is to receive the Intent as usual, but then forward it, while displaying some nice error message to the user that this app cannot handle the URL.

Of course another alternative is to just correctly intercept .compact (or generally, .*) links and convert the ".compact" to ".json".

The last option I can think of is to just ignore this bug, and hope that most links would be to i.reddit.com instead of www.reddit.com/.../.compact

**Comment by talklittle** [comment]
well, even i.reddit.com is troublesome. The comments links all point to www.reddit.com/.../.compact

see #146

**Comment by jc4p** [comment]
It would be best to ignore this bug, I don't see how someone could be clicking a .compact link without being on the mobile site to begin with. And adding another intent filter would add another possible place for a dialog box to come up to allow the user to select browser/RiF which could be annoying.

**Comment by talklittle** [comment]
Hey jc4p thanks for the input. I'm going to agree that ignoring this is the best approach for now.

I attempted to fix by sending out a new Intent in the case of an unsupported reddit URL, but that's a non-solution because it introduces the possibility of infinite loop hanging the device, if you select "Always open using this app" when launching an unsupported reddit URL.

So closing this issue as won't fix.
