### ISSUE TITLE
CommentsListActivity very slow some times

### ISSUE THREAD

**Issue by wac-** [talklittle/reddit-is-fun#129]
CommentsListActivity takes thousands of milliseconds to display comments sometimes. Doing traces with DDMS hints that the download, parsing and the post-processing is happening serially which could be hurting responsiveness. We should find a way to parse the comment JSON as it arrives. (This may have object reuse benefits as well. Jackson ObjectMapper seems to create a pretty substantial amount of object churn as it parses the input.)

logcat sez:
    01-03 19:32:39.429: DEBUG/CommentsListActivity.DownloadCommentsTask(29488): Content length: 22863
    01-03 19:32:40.425: DEBUG/CommentsListActivity.DownloadCommentsTask(29488): Successfully got OP listing[0]: modhash null
    01-03 19:32:41.488: DEBUG/Markdown(29488): linkText=And helped raise hundreds of thousands of dollars for DonorsChoose.org url=http://www.reddit.com/r/blog/comments/ddc0w/update_in_less_than_eight_hours_the_colbertrally/ title=null
    01-03 19:32:42.128: DEBUG/CommentsListActivity.DownloadCommentsTask(29488): parseCommentsJSON completed

**Comment by talklittle** [comment]
Fixed as part of bug #127
