### ISSUE TITLE
Top Text in self.posts is not displayed

### ISSUE THREAD

**Issue by glzt** [talklittle/reddit-is-fun#130]
Instead of the top comment of the OP, a red 'nsfw' followed by '0 cmnts' is displayed, the rest of the thread is fine.
Didn't have this issue with the previous version.

**Comment by talklittle** [comment]
Applies to HTC Wildfire and Dell Mini X10, and possibly others

**Comment by KoenRijpstra** [comment]
I had to revert back to 1.0.1
I couldn't download 1.0.3 got an error message:access denied

**Comment by pakesson** [comment]
Fixed in pakesson/reddit-is-fun@127b6465bb85c71c449a (I've added a pull request)

**Comment by talklittle** [comment]
amazing!! thank you pakesson, completely missed the fact that these are smaller devices... pulled and updating the apk now!
