### ISSUE TITLE
Increase size of thumbnail area for easier clicking.

### ISSUE THREAD

**Issue by cpettit** [talklittle/reddit-is-fun#139]
This issue is apparent on my tablet (Nook color rooted). I haven't really tested it out on smaller screens yet.  The thumbnail/arrow on the right is easy to miss when clicking, thus prompting the Link/Comments dialog.

Proposed solution: Increse the height to 100% of the box and right-align it flush with the parent to ensure striking the icon when clicking on the right side of the title box.

**Comment by talklittle** [comment]
good idea, maybe should add a clickable 100% height invisible container containing the thumbnail to avoid undesired image stretching.

**Comment by talklittle** [comment]
fixed on private branch. does not stretch to entire height of list item; see commit note for why I think that's the case

**Comment by talklittle** [comment]
disregard previous comment. expanded all the way to fit
