### ISSUE TITLE
Theme swap bug

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#144]
(when changing to dark theme) Text changes, but background remains white.

UPDATE:
Works when closing app and launching a fresh instance.

**Comment by normanthesquid** [comment]
I also experience this issue. Considering how bright the xooms screen is, would be nice to have it fixed. How can I help?

**Comment by talklittle** [comment]
This bug is weird, since the background color should be set to black, and shouldn't have anything to do with phone-model-specific themes. I'm guessing/hoping the bug refers to the immediate color swap rather than the fresh app load.

Have you tried setting the theme to black, closing out of the app completely by pressing Back a few times, and relaunching the app? Let me know if that helps. Thanks!

**Comment by normanthesquid** [comment]
Actually, that did work. interesting

**Comment by talklittle** [comment]
Ok thanks for the info, now I know which piece of the code contains the bug.

**Comment by pipwilson** [comment]
I see this same issue on the Asus Transformer.

**Comment by talklittle** [comment]
User reported it on Ice Cream Sandwich. Problem goes away, as on other devices, when you close out of app and relaunch.

**Comment by talklittle** [comment]
fixed in devel branch. instead of trying to hack around theme swap, simply relaunch Activity

http://stackoverflow.com/questions/2486934/programmatically-relaunch-recreate-an-activity
