### ISSUE TITLE
Switch menu items

### ISSUE THREAD

**Issue by jk3us** [talklittle/reddit-is-fun#145]
I'd rather see "jk3us's profile" on the main menu and the logout option under more.  Maybe we could just switch those two options?

**Comment by jk3us** [comment]
additionally, how about a confirmation when logging out?  I accidentally hit that item twice yesterday :(

**Comment by talklittle** [comment]
Ok, I'll switch Logout with one of the others, probably Profile like you suggested. (Inbox was another candidate, but there are already orangered notifications for mail, so Profile is a better choice.)

**Comment by talklittle** [comment]
Swapped logout with profile.
