### ISSUE TITLE
Log out confirmation

### ISSUE THREAD

**Issue by miika** [talklittle/reddit-is-fun#147]
I find it hard to believe that I'm not the only one who occasionally when trying to hit "refresh" or "pick subreddit" instead hit the "logout"-button.

Can we add at least a confirmation for logging out (i.e "Are you sure you want to log out?") to prevent accidental logouts. This is mainly irritating for us who use more complicated passwords as input takes quite a while.

**Comment by blueyed** [comment]
1) another idea would be to move the Logout button into a second level menu (e.g. with "options" although it does not fit there really).
2) there's a "Quit confirmation" setting already, maybe it could get named more general ("Confirm logout and quit") and used for this purpose, too?
