### ISSUE TITLE
Not Showing in AppDrawer

### ISSUE THREAD

**Issue by BrutalSauce** [talklittle/reddit-is-fun#167]
Installed new update and is no longer showing in the app drawer. Uninstalled and reinstalled still not showing.

**Comment by talklittle** [comment]
Hi can you give more details? Which Android version and phone model?
Using any special apps to control the app drawer contents? Thanks.

On Thu, Aug 11, 2011 at 3:37 PM, BrutalSauce
reply@reply.github.com
wrote:

**Comment by BrutalSauce** [comment]
I figured it out. It was an issue with GO Launcher.

**Comment by talklittle** [comment]
Cool. Thanks for letting me know what the issue was.

On Thu, Aug 11, 2011 at 7:08 PM, BrutalSauce
reply@reply.github.com
wrote:
