### ISSUE TITLE
Saving posts

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#18]
Ability to create/access saved posts

**Comment by dsoklic** [comment]
You mean like bookmarks?

**Comment by talklittle** [comment]
Yep- integration with the existing reddit "save" post feature and the "saved" thread listing.

Part of the reason would be some people like saving posts from phone to read later on their desktop or vice versa.

**Comment by talklittle** [comment]
I put "pending" because it seems like fernandotakai got it working. awaiting his pull request

**Comment by talklittle** [comment]
now in 0.9.3
