### ISSUE TITLE
Broken markdown lists. Comments cut off.

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#21]
Hello,

I really enjoy this application, but I noticed an error with the way some posts are rendered.

Check out this post:

http://reddit.com/r/WeAreTheMusicMakers/comments/a7wmz/heres_a_picture_of_me_in_my_studio_anyone_else/

When viewed from within 'reddit is fun', many posts with links are truncated in strange places -- notably, one by user locutor and one by user robhutten.

I've only just now noticed this phenomenon, but I can recall many other instances where people had links in their posts and referred to something like "the third link", which only confused me.

Any thoughts? Thanks for writing this app, by the way -- it's a real lifesaver. The m.reddit.com site was my previous way to check reddit on the go.

**Comment by avj** [comment]
Ah, perfect. I came to copy the email report here, but you're way ahead of me!

**Comment by talklittle** [comment]
fixed in 0.8.4. the problem was an overly greedy regex using the DFA automaton
