### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by sxe** [talklittle/reddit-is-fun#222]
Hi there, 

it seems the last update has some kind of regression. 
With version 1.2.1.3 rif had suddenly a lot smoother scrolling. Many users confirmed this.

Sadly with the latest update (version 1.2.1.5) it went in the wrong direction again. Scrolling is laggy and slow now, no matter what settings i use. It is definitely a problem with the latest version because changing back to an old version fixes the issue.

Thx

**Comment by talklittle** [comment]
sorry this won't be fixed because the cacheColorHint is required for some devices.

**Comment by talklittle** [comment]
the relevant commits are
https://github.com/talklittle/reddit-is-fun/commit/c9b2a741042cee450992e08e185c2f0477bbab76

which reverts
https://github.com/talklittle/reddit-is-fun/commit/70eb9aaf7f60034156edc8fe6c136d86bb0010af

in case you are interested in building a custom one for yourself.

**Comment by sxe** [comment]
Thx for the info, i will stick with the old build i think. 
Maybe there is a solution in the future or i have to change the app. The current build is really unusable on devices with bigger screens (higher resolution).

**Comment by talklittle** [comment]
Bigger screens, interesting...

Actually I just googled a bit more and found http://stackoverflow.com/questions/7224244/listview-very-slow-when-scrolling-using-viewholder-recycling which seems to address it--if I simplify my layout XML, it might speed things up. I actually changed the layout significantly as part of another issue #139

If you wouldn't mind testing, I'm putting the preview apk here: https://github.com/talklittle/reddit-is-fun/reddit-is-fun_1.2.2pre.apk/qr_code

I'd like to know if slow scrolling only happens to the post list, or also comments within a given post? Thanks a lot!

**Comment by sxe** [comment]
Great you are working on it.

That preview build works slightly better than the last official version but not as good as 1.2.1.3.
I also noticed, that the list gets smoother when you scrolled down completely and then move up again. Maybe because the items are cached after that?

**Comment by talklittle** [comment]
Thanks a lot for trying it out! What you said about scrolling down and back up makes me hopeful--I think I'll fix that behavior as part of #197, which is the last bug fix I've slotted for this upcoming release.

**Comment by sxe** [comment]
ok cool. But just to make sure i you understand me right. With your latest fix, it is still bad and only a bit better, so not really a final fix but better than nothing i think? :) There is still ab BIG difference between your latest fix and version 1.2.1.3. Sry if you know that, i just want to make it clear.

**Comment by talklittle** [comment]
The preview version I uploaded still does some dumb things for fetching thumbnails. I was hoping that fixing #197, which I have not done yet, would at least bring the app to the state you described of being "smoother when you scrolled down completely and then move up again." Maybe not quite as good as 1.2.1.3, but I imagine a great improvement over 1.2.1.5.

Anyway I suppose I'll have to keep this ticket open and maybe do further investigation. Or if I get some good reports from users after the upcoming release 1.2.2, then I can close it! Crossing my fingers for the latter.

Thanks for your assistance with this one!

**Comment by sxe** [comment]
Thx to you for this app.

If you need further assistance let me know it.

**Comment by talklittle** [comment]
sxe, I wonder if you have tried the latest version, 1.2.2b? Is it any faster?

**Comment by sxe** [comment]
Hey talklittle, 
no its not really better. I'm not 100% sure how it works compared to the market version but if there is a difference its not noticeable.

Sry to disappoint you. :)

**Comment by talklittle** [comment]
Oh darn. I appreciate your help testing it out, thanks!

**Comment by sxe** [comment]
You are welcome, at any time.

**Comment by talklittle** [comment]
I'm glad to say I've finally found a way to address this issue to remove cacheColorHint, providing the huge scrolling speedup, while also getting rid of the gray/white background flickering on some devices.

Thanks sxe for your help the whole way through! I really appreciate it!

**Comment by sxe** [comment]
Hey, great to hear that. 
I'm exited to test the build as soon as it is available in the market. 
Thx for your work.

**Comment by sxe** [comment]
Just to let you know, it works now. Well done!

**Comment by talklittle** [comment]
Great. thanks!
