### ISSUE TITLE
Better handling of links to subreddits

### ISSUE THREAD

**Issue by phobiac** [talklittle/reddit-is-fun#224]
On the main website a subreddit name such as /r/test is turned into a link to www.reddit.com/r/test. Reddit is Fun seems to pick up that these are links, and displays them accordingly, but doesn't actually link to the subreddit in question. (They do not show up in the list of links when you long press on a comment)

**Comment by talklittle** [comment]
breaking the youtu.be links bug out into issue #228

**Comment by talklittle** [comment]
fixed

**Comment by talklittle** [comment]
still allows double linking e.g. if someone writes full URL http://www.reddit.com/r/test but that's ok because this way it also supports linking to subreddit in case of direct link to comment thread, like http://www.reddit.com/r/test/comments/o98h5/testing_links_to_other_subreddits_in_comments/

**Comment by talklittle** [comment]
disregard previous comment; handle "double-linking" by keeping track of start-end ranges and disallow linking to overlapping links
