### ISSUE TITLE
Will Reddit is Fun do something to show solidarity with Reddit's blackout on January 18th?

### ISSUE THREAD

**Issue by MatrixFrog** [talklittle/reddit-is-fun#233]
As you've probably heard [Reddit will be blacked out](http://blog.reddit.com/2012/01/stopped-they-must-be-on-this-all.html) this Wednesday. Maybe Reddit is Fun could do something to show solidarity: I assume the API will be down too, so if you do nothing, it will just look like reddit is down. Users who don't try to visit the site through a browser will just assume their servers are overloaded.

So instead, maybe you could push out an update in the next couple days, that makes it so when you try to load the app on Wednesday during the blackout, it just shows you an anti-SOPA message and points you to the reddit homepage, which I guess will have links to more anti-SOPA information.

Just an idea, let me know what you think...

**Comment by talklittle** [comment]
This is exactly what exists in version 1.3.0 released this morning :)

It posts a Toast saying "Let's Protest SOPA" and launches the In-app browser to go to http://www.reddit.com which, based on the blog post, should have more info talking about protesting PIPA and SOPA.

Thanks for the feedback!

**Comment by talklittle** [comment]
Hmm--looks like SOPA has been shelved. I hope reddit will still be protesting PIPA on Jan 18, which seems the more imminent threat (and probably has been all along considering how crazy SOPA was).
