### ISSUE TITLE
changing theme color to dark under settings

### ISSUE THREAD

**Issue by taofd** [talklittle/reddit-is-fun#244]
When changing theme from Light --> Dark under settings and then pressing back and hitting "yes, restart" on the modal dialog brings you back to the home page, but does not apply settings changes. This also does not work vice versa.

However, hitting the settings button and going directly to  "use dark theme" (not going all the way into settings) will work.

version: lite 2.0
device: galaxy nexus (4.0.2)
carrier: verizon

**Comment by talklittle** [comment]
Confirmed bug. Thanks
