### ISSUE TITLE
Selecting comment shouldn't cause vertical scroll

### ISSUE THREAD

**Issue by eemeli** [talklittle/reddit-is-fun#247]
Using 2.0.1, selecting a comment highlights it and adds action buttons below and above the comment. This causes the comment's text to move down, which is a bit jarring. Instead, the comment's text should stay in the same position as before, and the contents above the comment should be pushed up.

**Comment by talklittle** [comment]
Good idea, thanks for the suggestion.

**Comment by talklittle** [comment]
Fixed, will release this weekend. It looks much better with the change.
