### ISSUE TITLE
Editing comments exposes escaped html to user

### ISSUE THREAD

**Issue by nguyenmp** [talklittle/reddit-is-fun#249]
When the user edits a comment, the dialog box that displays the current state of the comment in an EditText has its text set to the HTML escaped version of the text.  If the user uses any characters that need to be HTML escaped,  on every edit, the previous text will be escaped again.

This bug is reproducible:

1) Post a self-text or comment that contains an ampersand or a less-than or greater-than character.
2) Select to edit the post/comment.
3) Do not change any of the text.  You will see escaped HTML such as `&amp;`
4) Submit the unaltered text and you'll see it posted the escaped HTML which must be escaped again.  You end up with posts that contain `&amp&amp&amp&amp;` after a few edits.

Semi-important.  Not gamebreaking but definitely noticeable.

**Comment by talklittle** [comment]
Thanks, this has been fixed and will go with the update at the end of this week.
