### ISSUE TITLE
View Parent/Context/All from direct comment link

### ISSUE THREAD

**Issue by jk3us** [talklittle/reddit-is-fun#250]
In the new version, following a direct link to a comment will display that comment with its children (like it does on reddit), but I don't see a way to view the parent all comments from there.  Context might be nice too (like context=3 or something).

**Comment by jk3us** [comment]
For example, go to this URL on your device and open it with RiF: http://www.reddit.com/r/Android/comments/qs11o/reddit_is_fun_20/c404del

**Comment by talklittle** [comment]
Thanks this is definitely an issue that will get resolved.

**Comment by talklittle** [comment]
fixed, added a link to parent and full thread in the comment nav (the blue that shows up when you click a comment)

will show up in next release after 2.0.3 which is currently in Google Play Store
