### ISSUE TITLE
cant subscribe to subreddit

### ISSUE THREAD

**Issue by justinabrahms** [talklittle/reddit-is-fun#256]
I tried to subscribe to r/Europe but was unable. If I search for Europe, I can navigate to it. It never populates into the list where I can hit the toggle button however. Another place I looked was in the context menu when on the actual subreddit.

**Comment by talklittle** [comment]
Thanks- confirmed bug, it should be adding to subreddits list but a regression caused it to not add.

**Comment by talklittle** [comment]
will be fixed in next version after 2.3.2
