### ISSUE TITLE
Freezing\Crashing on tablet

### ISSUE THREAD

**Issue by ghost** [talklittle/reddit-is-fun#257]
It appears that when using the dual pane feature on my table (Asus Transformer Prime) the app crashing to the homescreen constantly.  I usually browse 10 or so posts before I get kicked to the homescreen.  Sometimes when it crashes the left pane goes blank and it just sits like that.  I have to use the task manager for the tablet to shut it down.

With dual pane setting turned off everything seems to run smooth.

**Comment by talklittle** [comment]
Hi @zergbait sorry for the delay responding. I think the next version, which I'm going to release within a few days, should tremendously improve the performance on dual-pane. There was basically a huge memory leak. Thanks for reporting.

**Comment by ghost** [comment]
Fantastic to hear! Thanks for the update,  the dual pane feature is really
what sold me on Reddit Is Fun and I love using it.
On Jun 21, 2012 3:19 PM, "Andrew Shu" <
reply@reply.github.com>
wrote:

**Comment by cautionbug** [comment]
i realize this ticket is a year old, but hopefully this will still get through.

i'm having the same problem described above, on the same make/model tablet (ASUS TF201), using RIF 2.7.7 free version. i remember experiencing the crashes above, but now the app crashes completely.

The crashing has been happening through the last several versions, but has gotten significantly worse over time (more frequent, more easily). Clearing cache doesn't seem to remedy the problem. It crashes most easily on animated gifs and larger photos albums (quantity and/or file size). The app works perfectly on my phone, though.

If there's any hope this app is still maintained and this comment reaches someone, i'd be happy to provide additional info as needed to help fix the problem. This is the best reddit reader i've tried & i want to continue using it, but lately the crashing has been terrible.

Thanks.
