### ISSUE TITLE
hiding parent while loading more comments bug

### ISSUE THREAD

**Issue by scallopedllama** [talklittle/reddit-is-fun#259]
while reading comments, if you click to load more comments then, while the new comments are still loading, hide the parent, it will put the new comments under the parent of the now hidden comment.

to reproduce
look at the comments for a post. hit to load more comments on the first post that allows it.
while the new comments are loading (with no indicator they're loading), hide the parents post.

when the comments are loaded, they are put as comments to the post. not hidden comments to the previous comment.

**Comment by talklittle** [comment]
Thanks for reporting this. I can't get it to reproduce exactly as you described; there is indeed a bug where the newly loaded comments are not hidden, but they are inserted at the correct position.

What Android device and OS version are you using?

**Comment by scallopedllama** [comment]
I have an HTC inspire 4g running android 2.3.5 with HTC sense 3.5 (the
virtuous affinity ROM).

After looking at it further, I didn't notice the lines to the left so
you're right. They're nested properly but they aren't hidden properly.
On Jun 28, 2012 11:44 AM, "Andrew Shu" <
reply@reply.github.com>
wrote:

**Comment by talklittle** [comment]
Cool thanks for clarifying.

**Comment by talklittle** [comment]
fixed in development branch
