### ISSUE TITLE
Trackball & "next 25" button

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#26]
using trackball you cannot reach the <next 25> button.  Instead it simply highlights the field as if it was another story.  Eg.

```
[Story 23]
[Story 24]
[..(next 25)..]

highlights the '[....]' section beneath the button
```

**Comment by talklittle** [comment]
Tried using view.setFocusable(false) to no avail. Also view.setNextFocus{Up,Down,Left,Right}Id() but didn't work. darn.

**Comment by kostmo** [comment]
one-line fix:
getListView().setItemsCanFocus(true);

setFocusable() is apparently not needed.
Yee haw!

**Comment by talklittle** [comment]
Ahhhhh thanks so much! That was driving me crazy!
Well, you're on the contributors list now.
