### ISSUE TITLE
Widgets change subreddit

### ISSUE THREAD

**Issue by dmogle** [talklittle/reddit-is-fun#261]
I'm using version 2.4.5 on a Samsung Galaxy 2S.  I have 4 widgets on one of my homescreens, each for a different subreddit.  After a while they start changing to point to the same subreddit.  I'm not sure, but it seems like they point to the one that's been updated most recently.

**Comment by talklittle** [comment]
Thanks for reporting. Confirmed bug. This will be fixed in the next update within a couple days.

**Comment by dmogle** [comment]
Appears to be fixed in 2.4.7.  Thanks!

**Comment by talklittle** [comment]
Great thanks for following up!
