### ISSUE TITLE
Thumbnail cache never clears, causing system slowdown

### ISSUE THREAD

**Issue by Goldom** [talklittle/reddit-is-fun#264]
I'm not sure if it's by design or bug, but the downloaded thumbnails are never erased during normal use - neither clearing the app cache in the system settings nor clearing the history in the in-app settings will erase them. Only fully erasing the app's data or deleting them manually gets rid of them.

Though the files are tiny, the sheer number of them after several days of use causes my system to grind to a halt when performing drive space calculations (like in Settings > Apps or Settings > Storage). When I first figured out what was causing it and went to delete the thumbnails, there were so many that my file manager would freeze before it could open the folder.

I've now set up a Tasker task that clears out the folder once a day, solving the problem for me. But it ought to do that automatically in the app, or at least provide an on-demand method for emptying the folder.

**Comment by talklittle** [comment]
Hi @Goldom what version of the app are you using? In the latest version on Google Play, it should be clearing out thumbnails that are more than 3 days old, unless there is a major bug preventing it from doing so.

Or maybe you are suggesting that 3 days is too long of a time and it should be reduced?

**Comment by talklittle** [comment]
I'm releasing another update this morning 2.5.3a. It will clear cache every 36 hours instead of 72 hours.

**Comment by talklittle** [comment]
Also what's your Android device model and OS version?

**Comment by Goldom** [comment]
I have been using the latest versions as they come out, BUT I admit it took me a while to report this, and it's possible one of the versions already fixed it since I created the task - I know the problem existed between June and July, but I didn't figure out the cause until a few weeks ago. I think it started the same update that added the image saving feature.

I've updated to the new version now and have disabled my task, so I'll report back in 36 hours about whether they're clearing properly or not.

I'm using an Asus Transformer Prime, Android version is 4.0.3.

**Comment by talklittle** [comment]
Great thanks for the info. The cache cleanup code was added June 25 and a
bugfix released for it around July 9. Since then I haven't touched the
cache cleanup code.

**Comment by Goldom** [comment]
Okay, I watched the dates on the files, and those over 36 hours old are clearing properly. Not sure if they weren't before, or if 72 hours was just too long, but it seems okay now. Thanks!

**Comment by talklittle** [comment]
Sweet! Thanks for following up!
