### ISSUE TITLE
Feature request: Toggle to hide non-subscribed subreddits

### ISSUE THREAD

**Issue by zekesonxx** [talklittle/reddit-is-fun#269]
I get the fact that it displays subreddits you've recently viewed, but I don't see the point in having all the subreddits there, most of which I have never heard of.

**Comment by talklittle** [comment]
Hi this is by design, to assist with discoverability of the most popular
200 or so subreddits.

**Comment by zekesonxx** [comment]
Well I was meaning something along the lines of being able to turn it off. I guess my original post was worded badly.
