### ISSUE TITLE
Adjustable font size

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#29]
Need a way to specify font size in Settings

**Comment by TheClarkster** [comment]
I agree.  It might just be my eyes, but on devices with a higher resolution like my Nexus One I find I can only read it well while in bed.  While sitting in the car the font is too small and thin to see clearly that far from my face.

**Comment by talklittle** [comment]
Finally added a font size setting, in my development branch. The new feature will appear in next release.
