### ISSUE TITLE
Find on page

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#3]
You should be able to do a find on the current comments list and jump to the next comment containing that character string.

**Comment by kostmo** [comment]
I have just written a patch that implements this feature.  What's the best way to get it to you?

**Comment by talklittle** [comment]
optimally would be via github, but if more convenient, send me a patch at gmail talklittle.

Thanks a lot!

**Comment by blueyed** [comment]
There is something in: https://github.com/kostmo/reddit-is-fun/commits/
I have not tested if it still applies to current master, but it would be worth a shot.
@kostmo: what's the status of this. Have you just forgotten to submit it here?

**Comment by kostmo** [comment]
@blueyed: I have just merged my "find" implementation with the current master.  It still works!  The new code is in my fork.  What is the next step?

**Comment by blueyed** [comment]
@kostmo: create a "Pull request" from the GitHub UI (top right when in your repo).

**Comment by kostmo** [comment]
OK, pull request is sent.

**Comment by blueyed** [comment]
Awesome! Thank you!
For reference, it's here: https://github.com/talklittle/reddit-is-fun/pull/154

**Comment by talklittle** [comment]
feature implemented by kostmo. closing ticket
