### ISSUE TITLE
Incorrectly loading cached comments

### ISSUE THREAD

**Issue by flowardnut** [talklittle/reddit-is-fun#32]
Sometimes I'll be browsing in reddit, I'll click on a link, go to comments, and comments from my previous session will load. I'm trying to recreate it, I believe it has to do with sleeping the phone while reading comments.

Hardware: Motorola Droid

I downloaded the source code, fixing bugs are a great way of exploring the code repository :)

**Comment by talklittle** [comment]
I think it's fixed in 0.9.0+ with my sexy new caching scheme
