### ISSUE TITLE
Ability to skip the popup for thread lists

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#33]
Some people have asked for the option to skip the popup and have option to always do one of:
- goto link
- goto comments
- toggle vote

**Comment by samongoose** [comment]
I'm working on this and have it mostly ready.  My implementation makes launching the link the default action, and long click to launch the current dialog.

I was wondering what others thought would be the correct default settings to provide when this is released.  Also, how should these settings be exposed?  Allow them to set a regular and long click action?  Just toggle between the current implementation and what I've described above?  Thanks for any input.

**Comment by talklittle** [comment]
I think best would be just have 2 options (a toggle checkbox in settings) for the short-click to open link. Short click and long click by default would both do popup.

Was initially thinking to be able to set each function separately but that's kind of unnecessary clutter I think.

Thanks a lot!

**Comment by samongoose** [comment]
That option makes sense.  What would you like the default to be?

**Comment by talklittle** [comment]
I'd prefer just keeping default to be current behavior i.e. popup for short-click (plus opening popup for long-click for all cases). Although lots of people want the open-link to be default, I like the popup since I go to comments as often as the link itself. If I had statistics where the majority preferred the other way then of course I'd pick that instead.

I just remembered- I hope you remember to handle self-posts with your new behavior (i.e. goto comments instead of opening link in browser)

**Comment by talklittle** [comment]
Hey I finally got around to adding this in... sorry for the wait.

I also made an addition to resolve what the best default behavior is: on first launch, it will ask the user what they want to do (always open link, or show dialog). Afterwards it sticks with that behavior of course.

Thanks a lot!

**Comment by amardeepsingh** [comment]
What happened to this feature? It looks like its gone in .92c

**Comment by talklittle** [comment]
Sorry. Removed this feature. clicking thumbnails still goes directly to link.
I intend to replace the long-click behavior of threads. So I needed to switch things around. By adding the vote/comment/link dialog to long-click, I didn't have any room left for a context menu.

I think clicking the thumbnail works just as well, though. except for the trackball users unfortunately. But I need the extra context menu soon, for Hide and Save features.

**Comment by amardeepsingh** [comment]
Hm. Clicking on the thumbnail doesn't seem to work when the thumbnail is loading (which seems to go on forever for most thumbnails).  I have a nexus one. Couldn't the context menu have hide, save, show dialog as options?

**Comment by talklittle** [comment]
Yes that was a bug, already fixed in the devel branch.

Context menu -> Show dialog -- definitely not, because that is simply too many clicks. And I prefer not to take the vote/comments/link dialog things and stuff them into a context menu since it is pretty ugly. Sorry.

**Comment by amardeepsingh** [comment]
ok, how about this then:
context menu: show,, hide, comments
Then, you re-add the option to skip the popup (you could default it to the current behaviour).  Personally, I never use the popup and would like the option to skip it altogether.  I'm pretty lazy, so its mere existence, and hence extra tap, makes me avoid using this great app.  If you need help implementing this, I could pitch in.

**Comment by talklittle** [comment]
Feel free to make your own fork with the features you like.

As I said, there is no "extra tap" with the thumbnails. I'll release new version within couple days fixing the bug you mentioned with the loading thumbnails.

Sorry I am already well decided on this issue. Unless someone comes up with a great interface to replace the vote/link/comments dialog and context menu, it's not happening.
