### ISSUE TITLE
Hide Threads

### ISSUE THREAD

**Issue by amardeepsingh** [talklittle/reddit-is-fun#35]
Need the ability to hide an article, by pressing a button and/or swiping the article in the article list.  Should integrate with the reddit 'hide' feature

Additionally, it would be nice to have the option to automatically hide read articles and show hidden posts.

**Comment by talklittle** [comment]
finally implemented this. Still TODO: a page to view previously hidden posts...

**Comment by amardeepsingh** [comment]
Great.  When can we expect a release?

**Comment by talklittle** [comment]
soon; however the ability to view previously hidden posts will come further down the road sometime
