### ISSUE TITLE
Including the anchor text in the list of links in comment

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#38]
http://www.reddit.com/r/Android/comments/bmxxr/a_few_reddit_is_fun_thoughts/

**Comment by samongoose** [comment]
I'm interested in this feature, so I've started taking a stab at it.  There's no obvious good implementation here, at least to me.  After playing with a few different options, the one I like best is having the pop up initially appear as it does now, and then a long-click on a particular item will swap back and forth between anchor text and url.  Perhaps there should be an option for what the default should be?

I'm open to ideas for alternative approaches if anyone has them.

**Comment by talklittle** [comment]
Cool thanks for taking this up.

I was thinking about this too. Long-click works but users usually have trouble discovering long-clickable items... One idea I had: have the first item of the list toggle the URLs and stuff for the rest of the list items? I'm not entirely sure about the execution (would it just close and re-open the dialog?) but that might be a clean way to do it. And no preferences option would be required.

**Comment by talklittle** [comment]
merged fix by macieklen
