### ISSUE TITLE
Messages are not marked as read if "mark messages as read when I open my inbox" is off in reddit account

### ISSUE THREAD

**Issue by aarobc** [talklittle/reddit-is-fun#40]
It's handy not having all messages suddenly marked as read on the desktop, that way you know what you have and have not reviewed yet. If the setting is not selected then reddit is fun will not mark messages that you check as read, resulting in multiple notifications for the same message until you mark them as read in a browser.

**Comment by talklittle** [comment]
fixed in latest ver. If you click on the messages they are marked as read now.
