### ISSUE TITLE
NSFW Marker on threads

### ISSUE THREAD

**Issue by faux** [talklittle/reddit-is-fun#53]
Include a NSWF indicator on threads that have NSFW in the title:

Screenshots:
http://imgur.com/mb6TN.png
http://imgur.com/mfAQX.png

Patch here:
http://github.com/faux/reddit-is-fun/commit/672cf833e16ca384a1d3ad30cc480258a090617d

**Comment by talklittle** [comment]
Thanks. It looks good.

The ThingInfo includes a field "over_18" so maybe it is possible to get the NSFW threads with isOver_18() instead of regex. I don't mind changing it when I pull.

**Comment by faux** [comment]
Here is a commit with the changes you requested:

http://github.com/faux/reddit-is-fun/commit/50fd8d7929e47122e229330d153cd958c7295db9

**Comment by talklittle** [comment]
Thanks.  will put in next version probably within a couple days.

**Comment by talklittle** [comment]
pulled in devel
