### ISSUE TITLE
mute icon appears over "go to link" arrow

### ISSUE THREAD

**Issue by finerrecliner** [talklittle/reddit-is-fun#54]
I have the paid version of RIF. The new arrows on the right side of each item (that jump to the associated link) are cool, but when I click on them, an icon that represents "mute" appears overlaid. I cant imagine this is intended, so I wanted to bring it to your attention. Thanks!

**Comment by talklittle** [comment]
This was already fixed in 0.9.2c

**Comment by finerrecliner** [comment]
you guys work fast ;)

thanks!
