### ISSUE TITLE
Labeling OP

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#6]
I do not currently label the OP, mods, admins in comments list. I don't know if the info for mods/admins is in JSON. Of course the OP can be found by looking at the OP ThreadInfo.

I wasn't sure about this though, since I know some subreddits can disable it (and maybe for good reason).

Related: /r/TRUST blacks out everyone's name by default. How to handle stuff like that?

**Comment by DavidTWhite** [comment]
info definitely does not appear to be part of JSON. also, mods replies are not always highlighted. not sure how this is done just yet.

**Comment by talklittle** [comment]
added request to http://code.reddit.com/wiki/API_Requests

**Comment by talklittle** [comment]
OP is easy, done
mods/admins no info, so won't fix
