### ISSUE TITLE
Link/comments buttons unreadable after switching to landscape.

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#64]
Sometimes when you switch your phone to landscape mode then tap an item, the link and comments buttons show up about half their normal size and the words 'link' and 'comments' are unreadable. It appears to happen on items with very long headlines that fill up the majority of the screen. My phone is an HTC Incredible.

**Comment by DDRBoxman** [comment]
So we can either have it so that the headlines get cut off after a certain point or the container gets larger so that they are not all a uniform size

**Comment by talklittle** [comment]
> they are not all a uniform size

What is "they" in your sentence?

I think cutting the headlines is fine (set maxlines lower) since that is what I did for the low dpi layout

**Comment by DDRBoxman** [comment]
They refers to the containers that make up the listview

**Comment by DDRBoxman** [comment]
Okay I just realized that this is inside the dialog box...

**Comment by talklittle** [comment]
Haha ok. I was a little confused there

**Comment by DDRBoxman** [comment]
So as far as i can tell this bug does not exist.

**Comment by talklittle** [comment]
Haha... yeah I dunno. I'm guessing it's something weird with HTC Incredible. BTW the text from bugreport was copy/pasted from someone else, I don't actually have HTC Incredible so I can't test. Oh well. I'll just close bug. Thanks for looking into it!

**Comment by DDRBoxman** [comment]
http://i.imgur.com/GHEI3.jpg
My friend sent me that, ill look into it.

**Comment by talklittle** [comment]
Ah ok cool. Thanks.
