### ISSUE TITLE
Crash on rotate after replying

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#66]
"i'm on a Motorola Droid, Bugless Beast 0.3 (aosp froyo build)

the app crashes when i post a comment and then close the screen (switching the orientation back to portrait) while the "sending reply" dialog box is on the screen. it's consistent behavior.

hope this helps!"

**Comment by twistadias** [comment]
Tried to reproduce this on my nexus one running FR91 (unrooted) and it works fine all the time. The comment gets posted correctly.

**Comment by talklittle** [comment]
Thanks twistadias! Must have been fixed with the recent releases.
