### ISSUE TITLE
Broken links with '<' (less-than symbol)

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#67]
Such as:

http://www.montulli.org/theoriginofthe%3Cblink%3Etag

**Comment by jk3us** [comment]
this looks like it's actually a bug in reddit.  Find the url attribute: http://www.reddit.com/r/programming/comments/cmaam/i_would_like_to_publicly_state_that_at_no_time/.json

Also, there's this comment: http://www.reddit.com/r/programming/comments/cmaam/i_would_like_to_publicly_state_that_at_no_time/c0tlgzz

Edit: to complete the loop: http://code.reddit.com/ticket/945

**Comment by talklittle** [comment]
Cool thanks for looking into it. So I guess we can leave it for reddit to fix, instead of something like substituting
    &lt;
and
    &gt;
for
    %3C
and
    %3E?
