### ISSUE TITLE
Enable Apps2SD

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#69]
Enable apps2sd in AndroidManifest.xml
requires building against API level 8

I tried it briefly but had some crashes due to Android API 8. Need to debug further

**Comment by twistadias** [comment]
I just tried it on my nexus one and it works without any problems.
This was version 0.9.3b

**Comment by talklittle** [comment]
Cool. Did you modify AndroidManifest.xml and do it that way, or did you use some other way of putting app on SD card?

Unfortunately I'm not sure anymore that I can enable Apps2SD, since there are features (current and upcoming) that may break with it enabled...

**Comment by twistadias** [comment]
Juts from the AndroidManifest.xml

Changed "Install location" to "auto"

**Comment by talklittle** [comment]
breaks some stuff with widget and stuff. for now won't fix
