### ISSUE TITLE
Changing orientation while viewing subreddit causes return to default subreddit

### ISSUE THREAD

**Issue by kd7lxl** [talklittle/reddit-is-fun#74]
Steps to reproduce:
1. From vertical orientation: Menu, Pick Subreddit
2. Choose "Android" (or any other, or type a subreddit name)
3. Change to horizontal orientation
4. Menu, Refresh (or Sort By--anything that normally causes a reload)
5. Will be returned to default subreddit.

Changing orientation seems to cause reddit-is-fun to forget the current subreddit, so any reload will now return the default subreddit.

**Comment by talklittle** [comment]
Confirmed bug.

**Comment by talklittle** [comment]
fixed in my development branch. fix will appear in next release.
