### ISSUE TITLE
Subreddit name on front page missing in Landscape orientation; persists when rotated to Portrait

### ISSUE THREAD

**Issue by avj** [talklittle/reddit-is-fun#78]
Subreddit name on front page missing in Landscape orientation; persists when rotated to Portrait

To reproduce:
1. Hold device in Portrait orientation.
2. Fire up RIF and load reddit front page.
3. Rotate device to Landscape orientation.
4. Subreddit names formerly placed next to "NNN comments" are now missing.
5. Rotate back to Portrait; names still missing.
6. Do a refresh and subreddit names are back.

Using reddit is fun 0.9.6b on Android 2.1 on an HTC Hero.

**Comment by kd7lxl** [comment]
Same behavior occurs when starting in horizontal orientation:
1. In horizontal orientation, load front page.
2. Change to vertical orientation.
3. Subreddit labels gone.

**Comment by talklittle** [comment]
should be fixed in upcoming version
