### ISSUE TITLE
Bulleted lists broken

### ISSUE THREAD

**Issue by avj** [talklittle/reddit-is-fun#79]
Bulleted list display is broken.

Have a look at the text that is part of this submission:

http://www.reddit.com/r/IAmA/comments/czt5z/i_am_asian_american_raised_by_helicopter_parents/

The improper display holds true in comments as well.

**Comment by talklittle** [comment]
Confirmed. Damn, not sure about this one. Maybe have to simply display asterisks, or resort to a modified MarkdownJ and threaded processing...

**Comment by avj** [comment]
Asterisks seem suitable and computationally cost-effective. I think everyone would understand their purpose.

Thanks for clarifying as well. I forgot to specify bulleted lists.

**Comment by talklittle** [comment]
fixed in development branch. using asterisks in place of bullets.
