### ISSUE TITLE
Jump to a thread's subreddit

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#82]
In ThreadsListActivity would be convenient to have a way to jump to post's subreddit, probably by long-clicking if it doesn't fit in the popup dialog. Should be a very easy implementation

**Comment by jk3us** [comment]
This, and to go to a subreddit from the comments list.

**Comment by talklittle** [comment]
added these in private branch. now thinking would be nice to keep a recent subreddit history...

**Comment by jk3us** [comment]
Subreddit history would be great.  There are only about 2 that I ever specifically go to on a regular basis, and sometimes they don't show up in the "pick subreddit" list.
