### ISSUE TITLE
EVO thread_click_dialog layout issue

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#85]
I found a bug. On my EVO running stock 2.2 if I am in landscape orientation and go to a link the box for replying and link will pop up. But the buttons will be cut off. When I turn the device so it will orient in a portrait style, the title of the link turns to "blah blah blah" and the author is talk little. The reply and link buttons do not then work.

**Comment by talklittle** [comment]
screenshot: http://dl.dropbox.com/u/121731/reddit_is_fun_ui_bugs.jpg

**Comment by aitese** [comment]
Erm...the screenshot included with this bug is mine. I posted it to Reddit. I captured it on my HTC Desire, not an EVO.

**Comment by talklittle** [comment]
maybe fixed now with some recent fixes for ICS layout
