### ISSUE TITLE
Retrieving threads fails continually (usually 3G) (Vodafone?)

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#90]
Sometimes for no apparent reason, retrieving threads just keeps failing. May have different causes.

Seems to happen very often for users of Vodafone 3G, who report it working fine on wifi.

Reinstalling the app sometimes fixes it temporarily but then it reverts to broken behavior.

**Comment by Matt2012** [comment]
yes Vodafone 3G UK I have this issue

**Comment by sandeepthefifth** [comment]
Yup another confirmation - HTC Desire unrooted running 2.2 on Vodafone. Just had a OTA update but issue still exists. Doesn't retrieve threads at all when on 3G but works as expected with Wifi.

**Comment by pwcazenave** [comment]
Still get this error with the 1.1.0 update. 

HTC Magic with 2.2 update on Vodafone.

**Comment by talklittle** [comment]
I think may be due to packet filtering of non-HTML data by Vodafone. Therefore there is no way for me to fix it in my app, since I am almost always using the JSON reddit api.

I think I need to mark this bug as a won't fix. Sorry Vodafone users.

**Comment by andyvincent** [comment]
The problem is due to the Content-Length header being missing (NullPointerException)... I've fixed this and submitted a pull-request for you.

**Comment by talklittle** [comment]
Thanks for finding and fixing that, Andy!! Will push out the update shortly.
