### ISSUE TITLE
Ampersand (&) in link

### ISSUE THREAD

**Issue by talklittle** [talklittle/reddit-is-fun#92]
"whenever i follow a link with an ampersand in it, it inserts "amp;" after the ampersand and breaks the link, figured id give  you a heads up in case youb werent aware"

**Comment by vafada** [comment]
no one is inserting the "amp;", that;s how the reddit api return it. Here's a sample json data where a link contains an ampersand:

```
    "created": 1286044976.0, 
    "url": "http://www.newegg.com/Store/Category.aspx?Category=234 &amp; name=Keyboards-Mice", 
    "title": "mice",
```

Original link was:

http://www.newegg.com/Store/Category.aspx?Category=234 & name=Keyboards-Mice
- had to put spaces.. even github converts & to & amp;

**Comment by vafada** [comment]
i created a reddit ticket for this one... i dont think this is a bug of reddit-is-fun

http://code.reddit.com/ticket/1039

**Comment by vafada** [comment]
as per the reddit ticket... the HTML escape was intended to prevent XSS

**Comment by talklittle** [comment]
fixed in development branch
