### ISSUE TITLE
View reddit toolbar when linked to article from app

### ISSUE THREAD

**Issue by prunk** [talklittle/reddit-is-fun#94]
When following an article from the list on the app it takes me directly to the url of the article in question but the toolbar does not show up on this new page. However, if I open the app, then click on the menu to view in browser, then follow an article from there it will show the toolbar on the new page. 
If possible could you make an option available in the menu settings of the reddit is fun app to show the toolbar when following a link. This would fix a fair number of issues, such as commenting on a followed story without having to back-track.

**Comment by talklittle** [comment]
Instead of the toolbar, there is now a menu option while viewing the article to View comments, implemented in my private development branch. So, marking this issue as "won't fix"
